frase = 'Curso em Vídeo Python'
#print(frase[9:14:2])
#print(frase.count('o'))
#print(len(frase)
#print(frase.upper())
#print(frase.strip())
#print(frase.capitalize())
#print(frase.title())
#print(frase.replace('Python', 'Android'))
#print('Curso' in frase)
#print(frase.find('Vídeo'))
#divido = frase.split()
#print(divido [3][0])
frase = frase.split()
print('-'.join(frase))
